"""empty message

Revision ID: 44d962e243ae
Revises: edced445b59f
Create Date: 2026-02-01 19:16:53.249561

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '44d962e243ae'
down_revision: Union[str, Sequence[str], None] = 'edced445b59f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bienalquilado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mes_anio', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.add_column(sa.Column('fecha_inicio_contrato', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('fecha_pago_mensual', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('observaciones', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
        batch_op.alter_column('descripcion',
               nullable=True)
        batch_op.alter_column('disponible',
               nullable=True)
        batch_op.drop_column('fecha_inicio')
        batch_op.drop_column('fecha_pago')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bienalquilado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_pago', sa.DATE(), nullable=True))
        batch_op.add_column(sa.Column('fecha_inicio', sa.DATE(), nullable=True))
        batch_op.alter_column('disponible',
               nullable=False)
        batch_op.alter_column('descripcion',
               nullable=False)
        batch_op.drop_column('observaciones')
        batch_op.drop_column('fecha_pago_mensual')
        batch_op.drop_column('fecha_inicio_contrato')
        batch_op.drop_column('direccion')
        batch_op.drop_column('mes_anio')

    # ### end Alembic commands ###
