"""Crud Bienes

Revision ID: 49c1b8dc623f
Revises: 
Create Date: 2026-02-06 12:01:14.465170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '49c1b8dc623f'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('inquilino',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('domicilio', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('celular', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('condicion_iva', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cuit', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('bienalquilado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mes_anio', sa.Date(), nullable=False),
    sa.Column('nombre', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('descripcion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('direccion', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('precio_mensual', sa.Float(), nullable=False),
    sa.Column('fecha_inicio_contrato', sa.Date(), nullable=True),
    sa.Column('fecha_pago_mensual', sa.Date(), nullable=True),
    sa.Column('disponible', sa.Boolean(), nullable=True),
    sa.Column('observaciones', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('inquilino_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilino.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('bienalquilado')
    op.drop_table('inquilino')
    # ### end Alembic commands ###
