"""empty message

Revision ID: 51ed875d3736
Revises: 49c1b8dc623f
Create Date: 2026-02-14 09:34:44.669927

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '51ed875d3736'
down_revision: Union[str, Sequence[str], None] = '49c1b8dc623f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bienalquilado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_final_contrato', sa.Date(), nullable=True))
        batch_op.drop_column('fecha_inicio_contrato')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bienalquilado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_inicio_contrato', sa.DATE(), nullable=True))
        batch_op.drop_column('fecha_final_contrato')

    # ### end Alembic commands ###
