"""empty message

Revision ID: 614402efefca
Revises: 8a77319b110d
Create Date: 2026-02-15 18:52:55.041001

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '614402efefca'
down_revision: Union[str, Sequence[str], None] = '8a77319b110d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.alter_column('fecha_inicial',
               nullable=True)
        batch_op.alter_column('fecha_final',
               nullable=True)
        batch_op.alter_column('inquilino_id',
               nullable=True)
        batch_op.alter_column('bien_id',
               nullable=True)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('contrato', schema=None) as batch_op:
        batch_op.alter_column('bien_id',
               nullable=False)
        batch_op.alter_column('inquilino_id',
               nullable=False)
        batch_op.alter_column('fecha_final',
               nullable=False)
        batch_op.alter_column('fecha_inicial',
               nullable=False)

    # ### end Alembic commands ###
