"""empty message

Revision ID: 8a77319b110d
Revises: db6bc5ab3069
Create Date: 2026-02-15 18:36:05.201379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '8a77319b110d'
down_revision: Union[str, Sequence[str], None] = 'db6bc5ab3069'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contrato',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicial', sa.Date(), nullable=False),
    sa.Column('fecha_final', sa.Date(), nullable=False),
    sa.Column('contrato_vigente', sa.Boolean(), nullable=False),
    sa.Column('inquilino_id', sa.Integer(), nullable=False),
    sa.Column('bien_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bien_id'], ['bienalquilado.id'], ),
    sa.ForeignKeyConstraint(['inquilino_id'], ['inquilino.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contrato')
    # ### end Alembic commands ###
