"""empty message

Revision ID: db6bc5ab3069
Revises: 51ed875d3736
Create Date: 2026-02-14 10:05:17.150883

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'db6bc5ab3069'
down_revision: Union[str, Sequence[str], None] = '51ed875d3736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bienalquilado', schema=None) as batch_op:
        batch_op.drop_column('nombre')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bienalquilado', schema=None) as batch_op:
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(), nullable=False))

    # ### end Alembic commands ###
